### ISSUE TITLE
"Oferty pracy" > "Szukaj" function doesn't work

### ISSUE THREAD

**Issue by kuras098** [krzosa/OddJobsServiceFrontend#28]
1. run the application
2. click on `Rejestracja`
3. enter search values in the fields `Stanowisko, firma` and `Miasto`

![image](https://user-images.githubusercontent.com/62210045/82133022-e0528c80-97e6-11ea-8da5-65a3e1776fce.png)

4.Click on `Szukaj`

**the value entered in the input fields is not used when the button is clicked**

**Comment by kuras098** [comment]
error in the second paragraph, must be **`2. click on Oferty pracy`**

**Comment by krzosa** [comment]
Fixed
